#!/usr/bin/env php

<?php

  include_once 'vendor/autoload.php';


  

  use Symfony\Component\Console\Application;
  use Shadowapp\Console\Command\CreateController;
  use Shadowapp\Console\Command\CreateModel;


  $app = new Application('Shadow Framework','0.1');
  
  $app->add(new CreateController);
  $app->add(new CreateModel);  


  $app->run();
?>
